// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/menu": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/category/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/menu" | "/product/:id" | "/category/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/menu.tsx": {
    id: "routes/menu";
    page: "/menu";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/product/:id";
  };
  "routes/category.tsx": {
    id: "routes/category";
    page: "/category/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/menu": typeof import("./app/routes/menu.tsx");
  "routes/product": typeof import("./app/routes/product.tsx");
  "routes/category": typeof import("./app/routes/category.tsx");
};