// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/menu": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/category/:id": {
    params: {
      "id": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/metrics": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/categories/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/products/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/menu" | "/product/:id" | "/category/:id" | "/cart" | "/checkout" | "/admin" | "/admin/metrics" | "/admin/users" | "/admin/orders" | "/admin/orders/:id" | "/admin/categories" | "/admin/categories/:id/edit" | "/admin/products/:id/edit" | "/profile";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/menu.tsx": {
    id: "routes/menu";
    page: "/menu";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/product/:id";
  };
  "routes/category.tsx": {
    id: "routes/category";
    page: "/category/:id";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/metrics" | "/admin/users" | "/admin/orders" | "/admin/orders/:id" | "/admin/categories" | "/admin/categories/:id/edit" | "/admin/products/:id/edit";
  };
  "routes/admin/metrics.tsx": {
    id: "routes/admin/metrics";
    page: "/admin/metrics";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/admin/orders.tsx": {
    id: "routes/admin/orders";
    page: "/admin/orders";
  };
  "routes/admin/order-details.tsx": {
    id: "routes/admin/order-details";
    page: "/admin/orders/:id";
  };
  "routes/admin/categories.tsx": {
    id: "routes/admin/categories";
    page: "/admin/categories";
  };
  "routes/admin/category-edit.tsx": {
    id: "routes/admin/category-edit";
    page: "/admin/categories/:id/edit";
  };
  "routes/admin/product-edit.tsx": {
    id: "routes/admin/product-edit";
    page: "/admin/products/:id/edit";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/menu": typeof import("./app/routes/menu.tsx");
  "routes/product": typeof import("./app/routes/product.tsx");
  "routes/category": typeof import("./app/routes/category.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/admin/layout": typeof import("./app/routes/admin/layout.tsx");
  "routes/admin/metrics": typeof import("./app/routes/admin/metrics.tsx");
  "routes/admin/users": typeof import("./app/routes/admin/users.tsx");
  "routes/admin/orders": typeof import("./app/routes/admin/orders.tsx");
  "routes/admin/order-details": typeof import("./app/routes/admin/order-details.tsx");
  "routes/admin/categories": typeof import("./app/routes/admin/categories.tsx");
  "routes/admin/category-edit": typeof import("./app/routes/admin/category-edit.tsx");
  "routes/admin/product-edit": typeof import("./app/routes/admin/product-edit.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
};